### ISSUE TITLE
There are no channels or groups of such id: xxxxx

### ISSUE THREAD

**Issue by engineershamrock** [duck8823/Slack-RTM-Bot#17]
When communicating with this code using Slack you can trigger the above message which causes the code to stop processing API messages

Example 

There are no channels or groups of such id: D4QJMB5KK at /usr/local/share/perl/5.20.2/Slack/RTM/Bot/Information.pm line 80.

The only way I can trigger this is as follows. I have only one Slack account and did not want to get too deep here

- New bot, invited to a private group
- Use the bot
- Now open a private conversation with the bot

I assume the private conversation is considered a group/channel which the bot does not know about as it gets the list when it starts up.

If you restart your bot from this point then the code no longer throws this error so I assume the channel/group is now in the list downloaded upon startup.

**Comment by duck8823** [comment]
Thank you for reporting issue.
I tried above, and could reproduce it.

i'll try fix it. Please wait a while until new release.

thank you :D
