### ISSUE TITLE
Odd number of elements in anonymous hash at /usr/local/share/perl5/Slack/RTM/Bot.pm line 86

### ISSUE THREAD

**Issue by realflash** [duck8823/Slack-RTM-Bot#2]
The code in the synopsis doesn't work because of the curly braces in

`$bot->say({
    channel => '@username',
    text    => 'hello, world.'
});`

If you create a file with this code in it you get the above error. Remove the curly braces to makeit an array and then it works OK.

**Comment by duck8823** [comment]
Thanks for the report.
I fixed.  34fdeb9
