### ISSUE TITLE
Could you give an example of this working?

### ISSUE THREAD

**Issue by pwr22** [duck8823/Slack-RTM-Bot#21]
I've been struggling a bit to get the example from the MetaCPAN page to work. It manages to send a personal message to me but it doesn't seem to be able to post to `#general` or receive messages in it

Does it still work with the current version of the API?

**Comment by duck8823** [comment]
I tried [Synopsis](https://metacpan.org/pod/Slack::RTM::Bot#SYNOPSIS) and it worked.
Perhaps you does not invite bot in `#general` channel ?
Please invite your bot in `#general` channel and re-run your script

**Comment by pwr22** [comment]
Thanks, you're right. I'm new to the Slack API
