### ISSUE TITLE
Example event definition in synopsis does not result in any messages being printed

### ISSUE THREAD

**Issue by realflash** [duck8823/Slack-RTM-Bot#4]
In the synopsis you have the example definition:

`{
        channel => 'general',
        text    => /.*/
    },`

Used as is, the $bot->on method gets this as an argument:

`{
          'text' => 1,
          'channel' => 'publictest'
        };
`

which then results in a failed regex match later, and nothing being printed. I think a qr before the regex is missing. This seems to work:

```
$bot->on({
        channel => 'general',
        text    => qr/.*/
    },
    sub {
        my ($response) = @_;
        $log->info($response->{text});
    }
);
```

**Comment by duck8823** [comment]
Many thanks for your reporting.
I fixed it. 34fdeb9
