### ISSUE TITLE
Malformed JSON string in synopsis example

### ISSUE THREAD

**Issue by ibrierley** [duck8823/Slack-RTM-Bot#5]
I seem to get a strange error on one of our servers (basically a test server seems to work, but our live one doesn't), both are centos 6.6 with perl 5.14.2. I can't think of anything obvious different.

Nothing gets displayed, but after 10 secs or so, the following error pops up in the console, and process still running...

> > malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Message is too long")

Code is exactly the same as Synopsis. Not quite sure how to debug this further.

**Comment by duck8823** [comment]
Perhaps response from slack is not json string.  
I fixed to print unchanged response if not json string.  
I hope this change help to to solve problems.
